version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mars-probe-api
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:iqui1234@mysql:3306/mars_probe
    ports:
      - "9900:9900"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    command: mysqld --authentication_policy=mysql_native_password
    container_name: mysql-probe
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "iqui1234"
      MYSQL_DATABASE: "mars_probe"
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-piqui1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: